---

- block: 
  - include: call_script.yml
    vars:
      script_name: update_admin_password
      args:
        new_password: "{{ nexus_admin_password }}"
  rescue:
    - debug:
        msg: 'Script upload failed possible password reset'
    - name: First-time install admin password
      set_fact:
        current_nexus_admin_password: 'admin123'
    - include: call_script.yml
      vars:
        script_name: update_admin_password
        args:
          new_password: "{{ nexus_admin_password }}"


- name: Admin password changed
  set_fact:
    current_nexus_admin_password: "{{ nexus_admin_password }}"
  no_log: true