---   
- name: First-time install admin password
  set_fact:
    current_nexus_admin_password: 'admin123'
  when: nexus_data_dir_contents.stdout == ""

- name: Subsequent re-provision admin password
  set_fact:
    current_nexus_admin_password: "{{ nexus_admin_password }}"
  when: nexus_data_dir_contents.stdout != ""
  no_log: true

- block: 
  - name: Create directory to hold current groovy scripts for reference
    file:
      path: "{{ nexus_data_dir }}/groovy-raw-scripts/current"
      state: directory
      owner: root
      group: root

  - name: Upload new scripts
    synchronize:
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
      mode: push
      use_ssh_args: yes
      src: "files/groovy/"
      dest: "{{ nexus_data_dir }}/groovy-raw-scripts/new/"

  - name: Sync new scripts to old and get differences
    shell: 'rsync -ric {{ nexus_data_dir }}/groovy-raw-scripts/new/ {{ nexus_data_dir }}/groovy-raw-scripts/current/ | cut -d" " -f 2 | sed "s/\.groovy//g"'
    register: nexus_groovy_files_changed
    check_mode: no
    changed_when: false
    # simple check on changed files kept on host
    # skip ansible lint (we don't want to use synchronize module for this)
    args:
      warn: false

  - name: Declare new or changed groovy scripts in nexus
    include: declare_script_each.yml
    with_items: "{{ nexus_groovy_files_changed.stdout_lines}}"
  rescue:
    - debug:
        msg: 'Script upload failed possible password reset'
    - name: First-time install admin password
      set_fact:
        current_nexus_admin_password: 'admin123'
    - name: Declare new or changed groovy scripts in nexus
      include: declare_script_each.yml
      with_items: "{{ nexus_groovy_files_changed.stdout_lines}}"

